image: oktupol/bitbucket-pipelines-php71

pipelines:
  branches:
    master:
    - step:
        name: unit test
        caches:
          - composer
          - vendor-directory
        script:
          - echo $PDC_BASE_SSH_KEY > ~/.ssh/id_rsa.tmp # note: assumes base64 encoded ssh key without a passphrase
          - base64 -d ~/.ssh/id_rsa.tmp > ~/.ssh/id_rsa
          - chmod 600 ~/.ssh/id_rsa
          - base64 ~/.ssh/id_rsa
          - composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs
          - ./vendor/bin/phpunit --testsuite "Unit Test"
    - step:
        name: integration test
        caches:
          - composer
          - vendor-directory
        script:
          #- service mysql start
          - composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs
          #- chmod +x bin/install-wp-tests.sh
          #- bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest
          #- ./vendor/bin/phpunit --testsuite "Integration Test"

definitions:
  caches:
    vendor-directory: vendor
    
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'wordpress_test'
        MYSQL_ROOT_PASSWORD: 'root'